#!/bin/bash
# Copyright (c) 2025 Mihai Stancu (https://github.com/curatorium)

shellcheck -x bash-import ||
	(echo "ERROR: bash-import failed shellcheck." && exit 1);

bash-test bash-import.test > bash-import.test.md ||
	(echo "ERROR: import tests failed." && exit 1);

.deps/@readme > README.md;
git diff --quiet README.md ||
	(echo "Docs are out of date." && exit 1);

git diff --quiet bash-import.test.md ||
	(echo "Test reports are out of date.." && exit 1);
